### ISSUE TITLE
Consider changing the license?

### ISSUE THREAD

**Issue by necauqua** [Plenglin/newbase60-rs#4]
Sooo, GPL3 is a strictly copyleft license, meaning that if I (or anybody) were to use this crate I'd technically have to licence my whole project as GPL3 as well - which is slightly problematic as it's literally just a base conversion algorithm which should be basically in public domain anyway.

And because of that I doubt that it's possible to blame me if I wrote the algorithm on my own (because I don't want to be forced into GPL3) and it turned out to be basically identical because how else would you write it?

My go-to licence is MIT anyway (which is just "use it in any way if you include the LICENSE file cuz it has my name on top of it, attribution"), not like I'm personally planning on profitting from your hard work :stuck_out_tongue:

So can you please consider to relicence this under MIT, or the weird `MIT OR Apache 2.0` that's  standard for Rust crates?

I'd personally maybe would've gone with Unlicense or straight up public domain (since the original algorithm was made or at least brought to light by Tantek anyway and he probably wouldn't mind)

It's all just perfectionism at the end of it as I doubt you'd even ever know about my (still opensource, just not GPL3, if this pet doesn't even die before I push the first version) project using your lib if not for that long wall of text I just wrote :)

**Comment by ifd3f** [comment]
Sure, I can change the license. This was written a really long time ago and I've been wanting to update it anyways :)

**Comment by ifd3f** [comment]
Okay, it's now republished under MIT: https://crates.io/crates/newbase60
